//
//  main.cpp
//  testing
//
//  Created by Oliver Waldhorst on 14.12.17.
//  Copyright © 2017 Oliver Waldhorst. All rights reserved.
//

// DO NOT EDIT THIS FILE!!!

#define CATCH_CONFIG_MAIN  // This tells Catch to provide a main() - only do this in one cpp file
#include "catch.hpp"

