//
//  myfs-info.h
//  myfs
//
//  Created by Oliver Waldhorst on 07.09.17.
//  Copyright © 2017 Oliver Waldhorst. All rights reserved.
//

// DO NOT EDIT THIS FILE!!!

#ifndef myfs_info_h
#define myfs_info_h

struct MyFsInfo {
    char *logFile;
    char *contFile;
};

#endif /* myfs_info_h */
