//
//  mount.myfs.c
//  myfs
//
//  Created by Oliver Waldhorst on 02.08.17.
//  Copyright © 2017 Oliver Waldhorst. All rights reserved.
//

// DO NOT EDIT THIS FILE!!!

#include "wrap.h"

#include <fuse.h>
#include <stdio.h>

#include "myfs-info.h"

struct fuse_operations myfs_oper;

int main(int argc, char *argv[]) {
    int fuse_stat;
    
    myfs_oper.getattr = wrap_getattr;
    myfs_oper.readlink = wrap_readlink;
    myfs_oper.getdir = NULL;
    myfs_oper.mknod = wrap_mknod;
    myfs_oper.mkdir = wrap_mkdir;
    myfs_oper.unlink = wrap_unlink;
    myfs_oper.rmdir = wrap_rmdir;
    myfs_oper.symlink = wrap_symlink;
    myfs_oper.rename = wrap_rename;
    myfs_oper.link = wrap_link;
    myfs_oper.chmod = wrap_chmod;
    myfs_oper.chown = wrap_chown;
    myfs_oper.truncate = wrap_truncate;
    myfs_oper.utime = wrap_utime;
    myfs_oper.open = wrap_open;
    myfs_oper.read = wrap_read;
    myfs_oper.write = wrap_write;
    myfs_oper.statfs = wrap_statfs;
    myfs_oper.flush = wrap_flush;
    myfs_oper.release = wrap_release;
    myfs_oper.fsync = wrap_fsync;
    myfs_oper.setxattr = wrap_setxattr;
    myfs_oper.getxattr = wrap_getxattr;
    myfs_oper.listxattr = wrap_listxattr;
    myfs_oper.removexattr = wrap_removexattr;
    myfs_oper.opendir = wrap_opendir;
    myfs_oper.readdir = wrap_readdir;
    myfs_oper.releasedir = wrap_releasedir;
    myfs_oper.fsyncdir = wrap_fsyncdir;
    myfs_oper.init = wrap_init;
    
    // FsInfo will be used to pass information to fuse functions
    struct MyFsInfo *FsInfo;
    FsInfo= malloc(sizeof(struct MyFsInfo));
    
    char* containerFileName= NULL;
    char* logFileName= NULL;
    char* mountPointName= NULL;
    
    // parse arguments
    if(argc > 3) {
        // check if container file exists
        containerFileName= realpath(argv[1], NULL);
        if(containerFileName == NULL || access(containerFileName, R_OK & W_OK) == -1) {
            fprintf(stderr, "Error: Cannot access container file %s\n", argv[1]);
            exit(EXIT_FAILURE);
        }
        
        // check if logfile can be accessed
        FILE* logFile = fopen(argv[2], "w+");
        
        if(logFile == NULL || (logFileName= realpath(argv[2], NULL)) == NULL) {
            fprintf(stderr, "Error: Cannot access log file %s\n", argv[2]);
            exit(EXIT_FAILURE);
        }
        
        fclose(logFile);
        
        // check if mountpoint exists
        if((mountPointName= realpath(argv[3], NULL)) == NULL) {
            fprintf(stderr, "Error: Cannot access mount point %s\n", argv[3]);
            exit(EXIT_FAILURE);
        }
        
        // everything ok, lets go
        fprintf(stderr, "Containerfile= %s\n", containerFileName);
        fprintf(stderr, "Logfile=       %s\n", logFileName);
        fprintf(stderr, "Mountpoint=    %s\n", mountPointName);
        
        // container & log file name will be passed to fuse functions
        FsInfo->contFile= containerFileName;
        FsInfo->logFile= logFileName;
        
        // adjust arguments, add option "-s" for single threaded
        argv+= 1; argc-= 1;
        argv[1]= "-s";
    }
    else {
        fprintf(stderr, "Usage: %s containerfile logfile mountpoint\n", argv[0]);
        return (EXIT_FAILURE);
    }
    
    // call fuse initialization method
    fuse_stat = fuse_main(argc, argv, &myfs_oper, FsInfo);
    
    fprintf(stderr, "fuse_main returned %d\n", fuse_stat);
    
    // cleanup
    free(FsInfo);
    free(containerFileName);
    free(logFileName);
    free(mountPointName);
    
    return EXIT_SUCCESS;
}


